[package]
authors = ["Norberto Lopes <nlopes.ml@gmail.com>"]
categories = ["web-programming"]
description = "Actix-web middleware to expose Prometheus metrics"
documentation = "https://docs.rs/actix-web-prom"
edition = "2018"
exclude = [".gitignore", ".travis.yml"]
keywords = ["actix", "actix-web", "middleware", "prometheus", "web"]
license = "MIT"
name = "actix-web-prom"
readme = "README.md"
repository = "https://github.com/nlopes/actix-web-prom.git"
version = "0.5.1"

[badges]
travis-ci = {repository = "nlopes/actix-web-prom", branch = "master"}

[dependencies]
actix-http = "=3.0.0-beta.5"
actix-service = "=2.0.0-beta.5"
actix-web = {version = "=4.0.0-beta.5", default-features = false}
futures = "^0.3"
pin-project = "^1.0"
prometheus = {version = "^0.11", default-features = false}
